sonar.projectKey=devops-e2e-project
sonar.projectName=DevOps E2E App
sonar.sources=app,java-util/src/main/java
sonar.tests=app,java-util/src/test/java
sonar.test.inclusions=app/test_*.py,java-util/src/test/**/*Test.java
sonar.python.version=3.11
sonar.java.binaries=java-util/target/classes
